apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 80 #Service Port Connection
      targetPort: 8000 #Container Port Connection
      protocol: TCP
#Port is a port number of your service and the targetPort is the port number of your container
#In that case we're reflecting the connection from the port 80 of my service to a port 8000 from my app goserver